# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - GlobalMicro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_65bec24fa2e6484b9109aa79c77200a2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3a0da79b08124177853f67da24999340 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_65bec24fa2e6484b9109aa79c77200a2 }}/Global:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'GlobalMicro'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_377cc3686f42440fb72ca4133f0c275d }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_65bec24fa2e6484b9109aa79c77200a2 }}/Global:${{ github.sha }}'